title: maciak.org
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maciak.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LukeMaciak
github_username:  maciakl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
    win:
        output: true
    kb:
        output: true
    lin:
        output: true
    web:
        output: true
    tabletop:
        output: true
    gamedev:
        output: true
    rpg:
        output: true
    security:
        output: true
    lock:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - exclude.rsync
